// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"week4/app/book/internal/biz"
	"week4/app/book/internal/conf"
	"week4/app/book/internal/data"
	"week4/app/book/internal/server"
	"week4/app/book/internal/service"
	"week4/pkg/appmanage"
)

// Injectors from wire.go:

func initApp(db *conf.ConfDB, http *conf.HttpConf, grpc *conf.GrpcConf, customer *conf.Customer) *appmanage.AppManage {
	fakeDB := data.NewBD(db)
	bookRepo := data.NewBookRepo(fakeDB)
	customerClient := data.NewCustomerClient(customer)
	bookUsecase := biz.NewBookUsecase(bookRepo, customerClient)
	bookService := service.NewBookService(bookUsecase)
	httpServer := server.NewHttpServer(bookService, http)
	grpcServer := server.NewGrpcServer(bookService, grpc)
	appManage := appmanage.NewAppManage(httpServer, grpcServer)
	return appManage
}
